### ISSUE TITLE
What is get_tinymce_plugins?

### ISSUE THREAD

**Issue by romanvm** [ITCase-django/django-tinymce-4#3]
The Readme says:

> Add urls to urls.py for your project:
```
urlpatterns = patterns('',
  ...
  # TinyMCE plugins
  url(r'^get_tinymce_plugins/$', get_tinymce_plugins, name='get_tinymce_plugins'),
```

What is ``get_tinymce_plugins`` exactly? The app does not include an object with such name.

**Comment by jbreuer95** [comment]
+1

**Comment by movie4** [comment]
This old information^ not used in Django project. Thanks
PS - update to 0.0.14
