### ISSUE TITLE
Filebrowser does not allow adding images 

### ISSUE THREAD

**Issue by nat-** [ITCase-django/django-tinymce-4#4]
When I first load the file browser from tinymce4, i get two errors in the console.
![image](https://cloud.githubusercontent.com/assets/4308070/15410844/2060d75e-1e70-11e6-9724-8a6524323f12.png)

Then when selecting an image I get this 
![image](https://cloud.githubusercontent.com/assets/4308070/15410860/432fc4fc-1e70-11e6-9750-e0a58474a3e5.png)

**Comment by ChangeSomeCode** [comment]
what versions of django, django-grappelli, django-filebrowser, django-tinymce-4 you are using?
