### ISSUE TITLE
Cannot insert image with Django filebrowser

### ISSUE THREAD

**Issue by sxyu** [ITCase-django/django-tinymce-4#5]
The default configuration will not work properly with the Django filebrowser as the tiny_mce_popup.js file included in this project is overridden by grappelli's original file, which does not work with TinyMCE 
The INSTALLED_APPS order does not seem to help.

*I had to copy the file into my site's own static directory for it to work*

To replicate:
1. Create new project
2. Install as instructed in the readme:
    * pip install git+git://github.com/ITCase-django/django-tinymce-4
    * add settings, in order
3. Create model, etc. using TinyMCE.
4. Go to the page in the browser. Click the image icon in the editor.
5. Click the browse for files icon.
6. Click the select button
7. Nothing happens. Console shows errors.

**Comment by ChangeSomeCode** [comment]
Yeah, you're right. Order in readme is wrong.

Because `tiny_mce_popup.js` must be overridden, `tinymce_4` should be over `grappelli`.

I've added an [example](https://github.com/ITCase-django/django-tinymce-4/tree/master/example) where you can see settings for correct work.

Thanks!
